name: restaurant_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pmvvm: ^4.0.1
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  shimmer: ^2.0.0
  readmore: ^2.2.0
  maps_launcher: ^2.0.1
  url_launcher: ^6.1.5
  package_rename: ^1.0.0+1
  icons_launcher: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0


flutter:
  assets:
    - assets/img/
    - assets/
    - lib/data/
  uses-material-design: true

  
icons_launcher:
  image_path: 'assets/img/ic_launcher.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true